# Generated by Django 5.2.9 on 2025-12-30 21:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_actual",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad total en inventario",
                        verbose_name="Cantidad en Stock",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ubicación física en bodega (Ej: A-12-3)",
                        max_length=100,
                        verbose_name="Ubicación",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inventario",
                "verbose_name_plural": "Inventarios",
                "db_table": "inventarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("administrador", "Administrador"),
                            ("externo", "Externo"),
                        ],
                        default="administrador",
                        help_text="Administrador: acceso completo | Externo: solo visualización",
                        max_length=20,
                        verbose_name="Tipo de Usuario",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el usuario puede acceder al sistema",
                        verbose_name="Usuario Activo",
                    ),
                ),
                (
                    "fecha_ultimo_acceso",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Acceso"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Conversacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        help_text="Título generado automáticamente del primer mensaje",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True, verbose_name="Conversación Activa"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversación",
                "verbose_name_plural": "Conversaciones",
                "db_table": "conversaciones_chatbot",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nit",
                    models.CharField(
                        help_text="Número de Identificación Tributaria (9-15 dígitos)",
                        max_length=15,
                        unique=True,
                        verbose_name="NIT",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Razón social de la empresa",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        help_text="Dirección física de la empresa",
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        help_text="Número de contacto principal",
                        max_length=20,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Correo electrónico de contacto",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la empresa está activa en el sistema",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "empresas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["nit"], name="empresas_nit_f247f8_idx"),
                    models.Index(fields=["nombre"], name="empresas_nombre_7f64b8_idx"),
                    models.Index(fields=["activa"], name="empresas_activa_0b856e_idx"),
                    models.Index(fields=["email"], name="empresas_email_8d4c7f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[("user", "Usuario"), ("assistant", "Asistente")],
                        max_length=10,
                        verbose_name="Rol",
                    ),
                ),
                ("contenido", models.TextField(verbose_name="Contenido del Mensaje")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="lite_thinking_domain.conversacion",
                        verbose_name="Conversación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje",
                "verbose_name_plural": "Mensajes",
                "db_table": "mensajes_chatbot",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("salida", "Salida")],
                        max_length=20,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                ("motivo", models.TextField(blank=True, verbose_name="Motivo")),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del Movimiento"
                    ),
                ),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="lite_thinking_domain.inventario",
                        verbose_name="Inventario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Inventario",
                "verbose_name_plural": "Movimientos de Inventario",
                "db_table": "movimientos_inventario",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        help_text="Código único del producto (se genera automáticamente si está vacío)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del producto",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada del producto",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "precio_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio del producto en dólares estadounidenses",
                        max_digits=12,
                        verbose_name="Precio USD",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("fisico", "Físico"),
                            ("digital", "Digital"),
                            ("servicio", "Servicio"),
                        ],
                        default="fisico",
                        max_length=20,
                        verbose_name="Tipo de Producto",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el producto está activo para venta",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "stock_minimo",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad mínima de stock antes de reabastecimiento",
                        verbose_name="Stock Mínimo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece el producto",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="lite_thinking_domain.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "productos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="inventario",
            name="producto",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventario",
                to="lite_thinking_domain.producto",
                verbose_name="Producto",
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["tipo"], name="usuarios_tipo_02599b_idx"),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["email"], name="usuarios_email_0ff7b3_idx"),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["activo"], name="usuarios_activo_3d49ab_idx"),
        ),
        migrations.AddConstraint(
            model_name="usuario",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__gt", "")),
                fields=("email",),
                name="unique_email",
            ),
        ),
        migrations.AddIndex(
            model_name="conversacion",
            index=models.Index(
                fields=["usuario", "-created_at"], name="conversacio_usuario_eb0a08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversacion",
            index=models.Index(fields=["activa"], name="conversacio_activa_a286f8_idx"),
        ),
        migrations.AddIndex(
            model_name="mensaje",
            index=models.Index(
                fields=["conversacion", "timestamp"],
                name="mensajes_ch_convers_360756_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mensaje",
            index=models.Index(fields=["rol"], name="mensajes_ch_rol_abd22a_idx"),
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(
                fields=["inventario", "-fecha"], name="movimientos_inventa_831c40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(fields=["tipo"], name="movimientos_tipo_af40b1_idx"),
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(fields=["fecha"], name="movimientos_fecha_c137fc_idx"),
        ),
        migrations.AddConstraint(
            model_name="movimientoinventario",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)),
                name="cantidad_movimiento_positiva",
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["codigo"], name="productos_codigo_1fb639_idx"),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["nombre"], name="productos_nombre_d31432_idx"),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["empresa", "activo"], name="productos_empresa_ad276a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["tipo"], name="productos_tipo_a03520_idx"),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.CheckConstraint(
                condition=models.Q(("precio_usd__gt", 0)), name="precio_usd_positivo"
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_minimo__gte", 0)),
                name="stock_minimo_no_negativo",
            ),
        ),
        migrations.AddIndex(
            model_name="inventario",
            index=models.Index(
                fields=["producto"], name="inventarios_product_33b811_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventario",
            index=models.Index(
                fields=["cantidad_actual"], name="inventarios_cantida_2cfef3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventario",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_actual__gte", 0)),
                name="cantidad_actual_no_negativa",
            ),
        ),
    ]
